[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build" # Command to build the app for production
  publish = "dist"          # Vite outputs built files to the "dist" directory by default
